name: LivesSMPPlugin
version: '${project.version}'
main: me.woodsmc.livessmpplugin.LivesSMPPlugin
api-version: 1.19
authors: [ WoodsMc ]
description: plugin for the LivesSMP
commands:
  lives:
    description: manage players lives
  tempban:
    description: temporarily ban players
  unban:
    description: unban banned or ran out of lives players
permissions:
  livessmp.lives.withdraw.command:
    description: allows access to /lives withdraw
  livessmp.lives.set.command:
    description: allows access to /lives set
  livessmp.lives.add.command:
    description: allows access to /lives add
  livessmp.lives.remove.command:
    description: allows access to /lives remove
